### ISSUE TITLE
Not working with XCode 8.3

### ISSUE THREAD

**Issue by dboydor** [50ButtonsEach/fliclib-ios#27]
I upgraded to XCode 8.3 and now I get linker errors as follows when building my project.  Also have same issues with your "ios-boilerplate-swift" project.

Do you know what might be wrong?  Does it just require you to compile against 8.3 for the framework?

ld: warning: ignoring file /Users/dboyd/dev/assure/assure-ios/fliclib.framework/fliclib, missing required architecture i386 in file /Users/dboyd/dev/assure/assure-ios/fliclib.framework/fliclib (2 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SCLFlicButton", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_SCLFlicManager", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
